### ISSUE TITLE
Error building project on Android Studio

### ISSUE THREAD

**Issue by agrenier-gnss** [sctg-development/RtkGps#27]
Hi Everyone, 

I am having issues when trying to build the project on Android Studio. I just cloned it from Github, and try to compile it, where an error rises in the External Native Build issues: "Build command failed."

The exact logs of the error is join to this post, but I think the important part is:

`Build command failed.	
Error while executing process /home/antoine/Android/Sdk/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/home/antoine/StudioProjects/RtkGps/jni/Android.mk NDK_APPLICATION_MK=/home/antoine/StudioProjects/RtkGps/jni/Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-21 NDK_OUT=/home/antoine/StudioProjects/RtkGps/build/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=/home/antoine/StudioProjects/RtkGps/build/intermediates/ndkBuild/release/lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}	
Android NDK: WARNING: Ignoring unknown import directory: null/jni    	
Android NDK: WARNING: Unsupported source file extensions in /home/antoine/StudioProjects/RtkGps/jni/Android.mk for module proj    	
Android NDK:   proj4/src/pj_list.h proj4/src/proj_internal.h proj4/src/proj_math.h proj4/src/emess.h proj4/src/geocent.h    	
Android NDK: WARNING: Unsupported source file extensions in /home/antoine/StudioProjects/RtkGps/jni/Android.mk for module rtklib    	
Android NDK:   LOCAL_SRC_FILES +=    	`

I am new to Android Studio. I'm not sure if the error is due to my environment. I try to make in run both on Windows 10 and Ubuntu 18.04 and the same error rises. I have the latest version of Android Studio on both.

Is this a library missing issue or am I missing something when setting up the project ?

Thank you for your suggestions and help.

Regards,

[Build command failed._.txt](https://github.com/eltorio/RtkGps/files/3121162/Build.command.failed._.txt)

**Comment by tdurand** [comment]
I have the same error, have you been able to solve it ?

**Comment by kolesar-andras** [comment]
Relevant error message is this:

> make: *** No rule to make target `/home/antoine/StudioProjects/RtkGps/jni/proj4/src/PJ_latlong.c`, needed by `/home/antoine/StudioProjects/RtkGps/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/objs-debug/proj/proj4/src/PJ_latlong.o`.  Stop.

Problem is caused by missing file `jni/proj4/src/PJ_latlong.c`. It exists in the same folder named `jni/proj4/src/pj_latlong.c`. Note the case difference between `PJ` and `pj`. Developer used Windows that ignores filename case. On Linux it is a problem.

Solution:

    mv jni/proj4/src/pj_latlong.c jni/proj4/src/PJ_latlong.c
